name: smart_locker_windows
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_esc_pos_utils: ^1.0.1
  # flutter_pos_printer_platform_image_3: ^1.2.0
  gallery_saver: ^2.3.2
  gif_view: ^0.3.1
  hydrated_bloc: ^9.1.3
  image_picker: ^1.0.7
  logger: ^2.4.0
  mobile_scanner: ^2.0.0
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  # serial_communication: ^0.0.2
  timer_count_down: ^2.2.2
  uhf_c72_plugin: ^1.0.1
  sizer:
  flutter_libserialport: ^0.4.0
  printing: ^5.13.2
  fluttertoast:


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
